language: node_js
node_js:
  - "node"
install:
  - npm install -g vuepress
script:
  - vuepress build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: .vuepress/dist
